FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    fastapi==0.111.0 \
    uvicorn==0.30.1 \
    mlflow==2.15.1 \
    scikit-learn==1.5.0 \
    prometheus-client==0.20.0 \
    boto3 \
    numpy \
    pydantic

COPY scripts/serve.py .

EXPOSE 8000

CMD ["python", "serve.py"]